<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use App\Helpers\AccountNumberHelper;

class AgentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('agents')->insert([
            [
                'name' => 'Ahmed Rahman',
                'phone' => '+8801712345679',
                'email' => 'ahmed.rahman@example.com',
                'email_verified_at' => now()->subDays(30),
                'password' => Hash::make('12345678'),
                'address' => 'House #45, Road #8, Banani, Dhaka-1213',
                'profile_picture' => 'profiles/ahmed_rahman.jpg',
                'agent_account_number' => 'AG' . str_pad(1, 8, '0', STR_PAD_LEFT),
                'total_balance' => 25000.00,
                'total_debit' => 15000.00,
                'total_credit' => 40000.00,
                'safety_balance' => 5000.00,
                'last_login_at' => now()->subHours(2),
                'last_login_ip' => '192.168.1.100',
                'last_login_user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'status' => 'active',
                'created_at' => now()->subDays(60),
                'updated_at' => now()->subHours(2),
            ],
            [
                'name' => 'Fatima Begum',
                'phone' => '+8801812345679',
                'email' => 'fatima.begum@example.com',
                'email_verified_at' => now()->subDays(25),
                'password' => Hash::make('12345678'),
                'address' => 'Apartment #12, Building #5, Agrabad, Chittagong-4100',
                'profile_picture' => 'profiles/fatima_begum.jpg',
                'agent_account_number' => 'AG' . str_pad(2, 8, '0', STR_PAD_LEFT),
                'total_balance' => 150000.00,
                'total_debit' => 75000.00,
                'total_credit' => 225000.00,
                'safety_balance' => 25000.00,
                'last_login_at' => now()->subDays(1),
                'last_login_ip' => '192.168.1.101',
                'last_login_user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
                'status' => 'active',
                'created_at' => now()->subDays(45),
                'updated_at' => now()->subDays(1),
            ],
            [
                'name' => 'Karim Hossain',
                'phone' => '+8801912345679',
                'email' => 'karim.hossain@example.com',
                'email_verified_at' => now()->subDays(20),
                'password' => Hash::make('12345678'),
                'address' => 'Village: Shibganj, Upazila: Sylhet Sadar, District: Sylhet',
                'profile_picture' => 'profiles/karim_hossain.jpg',
                'agent_account_number' => 'AG' . str_pad(3, 8, '0', STR_PAD_LEFT),
                'total_balance' => 75000.00,
                'total_debit' => 30000.00,
                'total_credit' => 105000.00,
                'safety_balance' => 15000.00,
                'last_login_at' => now()->subHours(6),
                'last_login_ip' => '192.168.1.102',
                'last_login_user_agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
                'status' => 'active',
                'created_at' => now()->subDays(35),
                'updated_at' => now()->subHours(6),
            ],
            [
                'name' => 'Nusrat Jahan',
                'phone' => '+8801612345679',
                'email' => 'nusrat.jahan@example.com',
                'email_verified_at' => now()->subDays(15),
                'password' => Hash::make('12345678'),
                'address' => 'House #78, Road #3, Rajshahi University Area, Rajshahi-6205',
                'profile_picture' => 'profiles/nusrat_jahan.jpg',
                'agent_account_number' => 'AG' . str_pad(4, 8, '0', STR_PAD_LEFT),
                'total_balance' => 50000.00,
                'total_debit' => 20000.00,
                'total_credit' => 70000.00,
                'safety_balance' => 10000.00,
                'last_login_at' => now()->subDays(3),
                'last_login_ip' => '192.168.1.103',
                'last_login_user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'status' => 'inactive',
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(3),
            ],
            [
                'name' => 'Imran Ali',
                'phone' => '+8801512345679',
                'email' => 'imran.ali@example.com',
                'email_verified_at' => now()->subDays(10),
                'password' => Hash::make('12345678'),
                'address' => 'House #56, Road #8, Khalishpur, Khulna-9000',
                'profile_picture' => 'profiles/imran_ali.jpg',
                'agent_account_number' => 'AG' . str_pad(5, 8, '0', STR_PAD_LEFT),
                'total_balance' => 0.00,
                'total_debit' => 50000.00,
                'total_credit' => 50000.00,
                'safety_balance' => 0.00,
                'last_login_at' => now()->subDays(7),
                'last_login_ip' => '192.168.1.104',
                'last_login_user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15',
                'status' => 'suspended',
                'created_at' => now()->subDays(25),
                'updated_at' => now()->subDays(7),
            ],
            [
                'name' => 'Sabina Yasmin',
                'phone' => '+8801412345679',
                'email' => 'sabina.yasmin@example.com',
                'email_verified_at' => now()->subDays(5),
                'password' => Hash::make('12345678'),
                'address' => 'House #23, Road #12, Mirpur, Dhaka-1216',
                'profile_picture' => 'profiles/sabina_yasmin.jpg',
                'agent_account_number' => 'AG' . str_pad(6, 8, '0', STR_PAD_LEFT),
                'total_balance' => 125000.00,
                'total_debit' => 60000.00,
                'total_credit' => 185000.00,
                'safety_balance' => 20000.00,
                'last_login_at' => now()->subHours(1),
                'last_login_ip' => '192.168.1.105',
                'last_login_user_agent' => 'Mozilla/5.0 (Android 11; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0',
                'status' => 'active',
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subHours(1),
            ],
            [
                'name' => 'Rashid Khan',
                'phone' => '+8801312345679',
                'email' => 'rashid.khan@example.com',
                'email_verified_at' => now()->subDays(3),
                'password' => Hash::make('12345678'),
                'address' => 'House #67, Road #9, Uttara, Dhaka-1230',
                'profile_picture' => 'profiles/rashid_khan.jpg',
                'agent_account_number' => 'AG' . str_pad(7, 8, '0', STR_PAD_LEFT),
                'total_balance' => 30000.00,
                'total_debit' => 15000.00,
                'total_credit' => 45000.00,
                'safety_balance' => 7500.00,
                'last_login_at' => now()->subHours(12),
                'last_login_ip' => '192.168.1.106',
                'last_login_user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'status' => 'active',
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subHours(12),
            ],
            [
                'name' => 'Ayesha Sultana',
                'phone' => '+8801212345679',
                'email' => 'ayesha.sultana@example.com',
                'email_verified_at' => now()->subDays(1),
                'password' => Hash::make('12345678'),
                'address' => 'House #89, Road #15, Gulshan, Dhaka-1212',
                'profile_picture' => 'profiles/ayesha_sultana.jpg',
                'agent_account_number' => 'AG' . str_pad(8, 8, '0', STR_PAD_LEFT),
                'total_balance' => 80000.00,
                'total_debit' => 40000.00,
                'total_credit' => 120000.00,
                'safety_balance' => 15000.00,
                'last_login_at' => now()->subHours(3),
                'last_login_ip' => '192.168.1.107',
                'last_login_user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
                'status' => 'active',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subHours(3),
            ],
        ]);
    }
}
